export const CONFIG = {
  // GitHub configuration
  github: {
    token: process.env.GITHUB_TOKEN || '',
    repoOwner: process.env.GITHUB_REPO_OWNER || '',
    repoName: process.env.GITHUB_REPO_NAME || '',
    apiUrl: 'https://api.github.com',
  },
  
  // AI/LLM configuration
  ai: {
    provider: 'openai',
    apiKey: process.env.OPENAI_API_KEY || '',
    model: 'gpt-4',
  },
  
  // Workflow configuration
  workflow: {
    branchPrefix: 'mastra-auto',
    commitMessage: 'feat: automated code changes via Mastra AI',
    prTitle: 'Automated changes via Mastra AI',
    prBody: 'This PR was automatically generated by Mastra AI workflow.',
  },
  
  // Agent configuration
  agent: {
    prompt: "You are a Senior Typescript Developer specialized in developing scalable applications using TDD, clean arch and BDD",
    maxTokens: 4000,
    temperature: 0.7,
  },
} as const;